1. public_api.py
Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
  File "/opt/tljh/user/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
  File "/opt/tljh/user/lib/python3.6/socket.py", line 745, in getaddrinfo
OSError: [Errno 23] Too many open files in system
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "/opt/tljh/user/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
  File "/opt/tljh/user/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
  File "/opt/tljh/user/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
  File "/opt/tljh/user/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f8bf407e940>: Failed to establish a new connection: [Errno 23] Too many open files in system
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
  File "/opt/tljh/user/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
  File "/opt/tljh/user/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='public.bitbank.cc', port=443): Max retries exceeded with url: /eth_jpy/ticker (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8bf407e940>: Failed to establish a new connection: [Errno 23] Too many open files in system',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.6/site-packages/python_bitbankcc/public_api.py", line 46, in get_ticker
  File "/opt/tljh/user/lib/python3.6/site-packages/python_bitbankcc/public_api.py", line 41, in _query
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/api.py", line 75, in get
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/api.py", line 60, in request
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='public.bitbank.cc', port=443): Max retries exceeded with url: /eth_jpy/ticker (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8bf407e940>: Failed to establish a new connection: [Errno 23] Too many open files in system',))

2. private_api.py

Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.6/site-packages/python_bitbankcc/private_api.py", line 79, in get_asset
    return self._get_query('/user/assets', {})
  File "/opt/tljh/user/lib/python3.6/site-packages/python_bitbankcc/private_api.py", line 67, in _get_query
    response = requests.get(uri, headers=headers)
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/tljh/user/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(32, 'EPIPE')",))